from proalgotrader_core.args_manager import ArgsManager as ArgsManager

__test__: dict

class Api:
    def __init__(self, *args, **kwargs) -> None: ...
    def create_order(self, *args, **kwargs): ...
    def create_risk_reward(self, *args, **kwargs): ...
    def enter_position(self, *args, **kwargs): ...
    def exit_position(self, *args, **kwargs): ...
    def get_algo_session_info(self, *args, **kwargs): ...
    def get_base_symbols(self, *args, **kwargs): ...
    def get_broker_symbols(self, *args, **kwargs): ...
    def get_github_access_token(self, *args, **kwargs): ...
    def get_orders(self, *args, **kwargs): ...
    def get_positions(self, *args, **kwargs): ...
    def get_risk_reward(self, *args, **kwargs): ...
    def get_trades(self, *args, **kwargs): ...
    def get_trading_days(self, *args, **kwargs): ...
