# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/terraquantum/storage/v1alpha1/list_storages.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.terraquantum.storage.v1alpha1 import storage_pb2 as com_dot_terraquantum_dot_storage_dot_v1alpha1_dot_storage__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5com/terraquantum/storage/v1alpha1/list_storages.proto\x12!com.terraquantum.storage.v1alpha1\x1a/com/terraquantum/storage/v1alpha1/storage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"x\n\x13ListStoragesRequest\x12\x1d\n\nproject_id\x18\x01 \x01(\tR\tprojectId\x12\x42\n\x04type\x18\x02 \x01(\x0e\x32..com.terraquantum.storage.v1alpha1.StorageTypeR\x04type\"c\n\x14ListStoragesResponse\x12K\n\x08storages\x18\x01 \x03(\x0b\x32/.com.terraquantum.storage.v1alpha1.StorageProtoR\x08storagesB\xb8\x02\n%com.com.terraquantum.storage.v1alpha1B\x11ListStoragesProtoP\x01ZUterraquantum.swiss/tq42_grpc_client/com/terraquantum/storage/v1alpha1;storagev1alpha1\xa2\x02\x03\x43TS\xaa\x02!Com.Terraquantum.Storage.V1alpha1\xca\x02!Com\\Terraquantum\\Storage\\V1alpha1\xe2\x02-Com\\Terraquantum\\Storage\\V1alpha1\\GPBMetadata\xea\x02$Com::Terraquantum::Storage::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.storage.v1alpha1.list_storages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.com.terraquantum.storage.v1alpha1B\021ListStoragesProtoP\001ZUterraquantum.swiss/tq42_grpc_client/com/terraquantum/storage/v1alpha1;storagev1alpha1\242\002\003CTS\252\002!Com.Terraquantum.Storage.V1alpha1\312\002!Com\\Terraquantum\\Storage\\V1alpha1\342\002-Com\\Terraquantum\\Storage\\V1alpha1\\GPBMetadata\352\002$Com::Terraquantum::Storage::V1alpha1'
  _globals['_LISTSTORAGESREQUEST']._serialized_start=174
  _globals['_LISTSTORAGESREQUEST']._serialized_end=294
  _globals['_LISTSTORAGESRESPONSE']._serialized_start=296
  _globals['_LISTSTORAGESRESPONSE']._serialized_end=395
# @@protoc_insertion_point(module_scope)
