# coding: utf-8

"""
    Carrier API

    **Seaplane Global Messaging Service**  For information about authentication see [authentication](/docs/authentication)   # noqa: E501

    The version of the OpenAPI document: 1.1.0-beta
    Contact: support@seaplane.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import seaplane.gen.carrier
from seaplane.gen.carrier.models.http_client_output import (
    HttpClientOutput,
)  # noqa: E501
from seaplane.gen.carrier.rest import ApiException


class TestHttpClientOutput(unittest.TestCase):
    """HttpClientOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test HttpClientOutput
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `HttpClientOutput`
        """
        model = seaplane.gen.carrier.models.http_client_output.HttpClientOutput()  # noqa: E501
        if include_optional :
            return HttpClientOutput(
                url = 'www.example.com', 
                method = 'POST', 
                headers = {"X-HEADER-1":"Value 1","X-HEADER-2":"Value 2"}
            )
        else :
            return HttpClientOutput(
                url = 'www.example.com',
        )
        """

    def testHttpClientOutput(self):
        """Test HttpClientOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
