
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-20T12:39:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f52f1c81ac2a59eb1663e9672d0dea703b5bddf",
 "version": "1.6rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
