cluster = {
    "result": {
        "cluster-state": {
            "cache-slot": "1",
            "cluster-state": "cluster-active",
            "local-information": {
                "interface": {
                    "ha4": {
                        "ip-address": "169.254.0.1/24",
                        "port": "ethernet1/1",
                        "link-speed": "auto",
                        "link-duplex": "auto",
                    },
                    "ha4-backup": {
                        "ip-address": "169.253.0.1/24",
                        "port": "ethernet1/2",
                        "link-speed": "auto",
                        "link-duplex": "auto",
                    },
                },
                "cluster-id": "1",
                "description": {},
                "members-count": "3",
                "cluster-members": {
                    "serial-007954000450444": {
                        "synchronization-off": "False",
                        "synchronization-description": "woodlands-fw2",
                        "cluster-primary-ip": "169.254.0.2",
                        "cluster-backup-ip": "169.253.0.2",
                        "hostname": "woodlands-fw2",
                    },
                    "serial-007054000254790": {
                        "synchronization-off": "False",
                        "synchronization-description": "woodlands-fw3",
                        "cluster-primary-ip": "169.254.0.3",
                        "cluster-backup-ip": "169.253.0.3",
                        "hostname": "woodlands-fw3",
                    },
                },
            },
        }
    }
}

active_passive = {
    "result": {
        "enabled": "yes",
        "group": {
            "mode": "Active-Passive",
            "local-info": {
                "url-compat": "Unknown",
                "app-version": "8729-8157",
                "gpclient-version": "Not Installed",
                "build-rel": "10.1.4-h4",
                "ha2-port": "ethernet1/2",
                "av-version": "0",
                "ha1-encrypt-enable": "no",
                "url-version": "20240317.20237",
                "mgmt-hb": "configured",
                "platform-model": "PA-VM",
                "av-compat": "Unknown",
                "vpnclient-compat": "Unknown",
                "ha1-ipaddr": "169.250.0.1/24",
                "vm-license": "vm100",
                "ha2-macaddr": "4e:34:bd:08:06:02",
                "monitor-fail-holdup": "0",
                "priority": "10",
                "preempt-hold": "1",
                "state": "active",
                "version": "1",
                "promotion-hold": "2000",
                "threat-compat": "Unknown",
                "gpclient-compat": "Unknown",
                "state-sync": "HA1-peer-disconnected",
                "vm-license-compat": "Unknown",
                "addon-master-holdup": "500",
                "heartbeat-interval": "2000",
                "ha1-link-mon-intv": "3000",
                "hello-interval": "8000",
                "ha1-port": "ethernet1/1",
                "ha1-encrypt-imported": "no",
                "mgmt-ip": "192.168.255.16/24",
                "vpnclient-version": "Not Installed",
                "preempt-flap-cnt": "0",
                "DLP": "Unknown",
                "nonfunc-flap-cnt": "0",
                "threat-version": "8729-8157",
                "ha1-macaddr": "4e:34:bd:08:06:01",
                "vm-license-type": "vm100",
                "state-duration": "262857",
                "max-flaps": "3",
                "active-passive": {
                    "passive-link-state": "shutdown",
                    "monitor-fail-holddown": "1",
                },
                "mgmt-ipv6": {},
                "state-sync-type": "ethernet",
                "preemptive": "yes",
                "iot-version": "119-483",
                "mode": "Active-Passive",
                "build-compat": "Match",
                "iot-compat": "Unknown",
                "VMS": "Unknown",
                "app-compat": "Unknown",
            },
            "peer-info": {
                "app-version": "Unknown",
                "gpclient-version": "Unknown",
                "conn-down-reason": "Heartbeat ping failure",
                "url-version": "Unknown",
                "build-rel": "10.1.4-h4",
                "platform-model": "PA-VM",
                "vm-license": "vm100",
                "ha2-macaddr": "4e:34:bd:08:07:02",
                "priority": "20",
                "state": "unknown",
                "version": "0",
                "conn-mgmt": {
                    "conn-down-reason": "Heartbeat ping failure",
                    "conn-status": "down",
                    "conn-desc": "heartbeat status",
                },
                "iot-version": "Unknown",
                "conn-status": "down",
                "av-version": "Unknown",
                "vpnclient-version": "Unknown",
                "mgmt-ip": "192.168.255.17/24",
                "DLP": "Unknown",
                "conn-ha2": {
                    "conn-status": "up",
                    "conn-ka-enbled": "no",
                    "conn-primary": "yes",
                    "conn-desc": "link status",
                },
                "threat-version": "Unknown",
                "ha1-macaddr": "4e:34:bd:08:07:01",
                "conn-ha1": {
                    "conn-down-reason": "Heartbeat ping failure",
                    "conn-status": "down",
                    "conn-desc": "heartbeat status",
                },
                "vm-license-type": "Unknown",
                "state-duration": "112",
                "ha1-ipaddr": "169.250.0.2",
                "mgmt-ipv6": {},
                "preemptive": "yes",
                "mode": "Unknown",
                "VMS": "Unknown",
            },
            "link-monitoring": {
                "failure-condition": "any",
                "enabled": "yes",
                "groups": {},
            },
            "path-monitoring": {
                "virtual-wire": {},
                "failure-condition": "any",
                "enabled": "yes",
                "vlan": {},
                "virtual-router": {},
            },
            "running-sync": "unknown",
            "running-sync-enabled": "yes",
        },
    }
}

active_active = {
    "result": {
        "enabled": "yes",
        "group": {
            "mode": "Active-Active",
            "local-info": {
                "url-compat": "Mismatch",
                "app-version": "8823-8642",
                "vm-license-type": "vm100",
                "gpclient-version": "Not Installed",
                "build-rel": "10.1.3",
                "ha2-port": "ethernet1/2",
                "av-version": "4759-5277",
                "ha1-gateway": "192.168.255.1",
                "url-version": "20240317.20276",
                "ha1-backup-ipaddr": "169.254.0.1/24",
                "ha1-backup-macaddr": "82:2c:5b:be:ff:01",
                "platform-model": "PA-VM",
                "av-compat": "Match",
                "vpnclient-compat": "Match",
                "ha1-ipaddr": "192.168.255.11/24",
                "vm-license": "vm100",
                "ha2-macaddr": "82:2c:5b:be:ff:02",
                "monitor-fail-holdup": "0",
                "priority": "100",
                "preempt-hold": "1",
                "state": "active-primary",
                "version": "1",
                "promotion-hold": "2000",
                "threat-compat": "Match",
                "gpclient-compat": "Match",
                "state-sync": "Complete",
                "vm-license-compat": "Match",
                "addon-master-holdup": "500",
                "heartbeat-interval": "2000",
                "ha1-link-mon-intv": "3000",
                "hello-interval": "8000",
                "ha1-port": "management",
                "ha1-encrypt-imported": "no",
                "mgmt-ip": "192.168.255.11/24",
                "vpnclient-version": "Not Installed",
                "ha1-backup-port": "ethernet1/1",
                "preempt-flap-cnt": "0",
                "DLP": "Match",
                "nonfunc-flap-cnt": "0",
                "threat-version": "8823-8642",
                "ha1-macaddr": "82:2c:5b:be:ff:00",
                "ha3-macaddr": "82:2c:5b:be:ff:03",
                "state-duration": "62462",
                "max-flaps": "3",
                "ha1-encrypt-enable": "no",
                "mgmt-ipv6": {},
                "ha3-port": "ethernet1/3",
                "state-sync-type": "ethernet",
                "preemptive": "no",
                "iot-version": "119-483",
                "mode": "Active-Active",
                "build-compat": "Match",
                "active-active": {
                    "setup-rule": "ip-modulo",
                    "session-rule": "first-packet",
                    "tentative-hold": "60",
                    "device-id": "0",
                    "nw-cfg-sync-vrouter": "yes",
                    "nw-cfg-sync-qos": "no",
                },
                "iot-compat": "Match",
                "VMS": "Match",
                "app-compat": "Match",
            },
            "peer-info": {
                "app-version": "8823-8642",
                "gpclient-version": "Not Installed",
                "url-version": "20240317.20277",
                "ha1-backup-ipaddr": "169.254.0.2",
                "av-version": "4759-5277",
                "platform-model": "PA-VM",
                "ha1-ipaddr": "192.168.255.12",
                "vm-license": "vm100",
                "ha2-macaddr": "82:2c:5b:be:ff:12",
                "threat-version": "8823-8642",
                "priority": "100",
                "state": "active-secondary",
                "version": "1",
                "build-rel": "10.1.3",
                "conn-status": "up",
                "ha1-backup-macaddr": "82:2c:5b:be:ff:11",
                "vpnclient-version": "Not Installed",
                "mgmt-ip": "192.168.255.12/24",
                "ha3-macaddr": "82:2c:5b:be:ff:13",
                "DLP": "1.0.4",
                "conn-ha2": {
                    "conn-status": "up",
                    "conn-ka-enbled": "no",
                    "conn-primary": "yes",
                    "conn-desc": "link status",
                },
                "conn-ha3": {"conn-status": "up", "conn-desc": "link status"},
                "ha1-macaddr": "82:2c:5b:be:ff:10",
                "conn-ha1": {
                    "conn-status": "up",
                    "conn-primary": "yes",
                    "conn-desc": "heartbeat status",
                },
                "vm-license-type": "vm100",
                "state-duration": "61504",
                "mgmt-ipv6": {},
                "VMS": "2.1.9",
                "preemptive": "no",
                "iot-version": "119-483",
                "mode": "Active-Active",
                "active-active": {
                    "setup-rule": "ip-modulo",
                    "device-id": "1",
                    "session-rule": "first-packet",
                    "tentative-hold": "60",
                },
                "conn-ha1-backup": {
                    "conn-status": "up",
                    "conn-desc": "heartbeat status",
                },
            },
            "link-monitoring": {
                "failure-condition": "any",
                "enabled": "yes",
                "groups": {},
            },
            "path-monitoring": {
                "virtual-wire": {},
                "failure-condition": "any",
                "enabled": "yes",
                "vlan": {},
                "virtual-router": {},
            },
            "running-sync": "synchronized",
            "running-sync-enabled": "yes",
        },
    }
}
