from enum import Enum


class ClassificationModelType(str, Enum):
    RANDOM_FOREST_CLASSIFIER = "RANDOM_FOREST_CLASSIFIER"
    EXTRA_TREES_CLASSIFIER = "EXTRA_TREES_CLASSIFIER"
    LINEAR_SVM_CLASSIFIER = "LINEAR_SVM_CLASSIFIER"
    GRADIENT_BOOST_CLASSIFIER = "GRADIENT_BOOST_CLASSIFIER"
    XGB_CLASSIFIER = "XGB_CLASSIFIER"
    QDA_CLASSIFIER = "QDA_CLASSIFIER"
    NAIVE_BAYES_CLASSIFIER = "NAIVE_BAYES_CLASSIFIER"
    LOGISTIC_REGRESSION_CLASSIFIER = "LOGISTIC_REGRESSION_CLASSIFIER"
    EXPLAINABLE_BOOSTING_CLASSIFIER = "EXPLAINABLE_BOOSTING_CLASSIFIER"

    def __str__(self) -> str:
        return str(self.value)