import enum
from proalgotrader_core.protocols.enums.market_type import MarketType as MarketType
from proalgotrader_core.protocols.enums.product_type import ProductType as ProductType
from typing import Callable, ClassVar

__test__: dict

class AccountType(enum.Enum):
    __new__: ClassVar[Callable] = ...
    CASH_INTRADAY: ClassVar[AccountType] = ...
    CASH_POSITIONAL: ClassVar[AccountType] = ...
    DERIVATIVE_INTRADAY: ClassVar[AccountType] = ...
    DERIVATIVE_POSITIONAL: ClassVar[AccountType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[object]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    _value_repr_: ClassVar[None] = ...
