import typing_extensions

from iparapheur_provisioning.paths import PathValues
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_user_user_id import ApiProvisioningV1AdminUserUserId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id import ApiProvisioningV1AdminTenantTenantId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_workflow_definition_workflow_definition_key import ApiProvisioningV1AdminTenantTenantIdWorkflowDefinitionWorkflowDefinitionKey
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_user_user_id import ApiProvisioningV1AdminTenantTenantIdUserUserId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_templates_template_type import ApiProvisioningV1AdminTenantTenantIdTemplatesTemplateType
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_seal_certificate_seal_certificate_id import ApiProvisioningV1AdminTenantTenantIdSealCertificateSealCertificateId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_metadata_metadata_id import ApiProvisioningV1AdminTenantTenantIdMetadataMetadataId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_desk_desk_id import ApiProvisioningV1AdminTenantTenantIdDeskDeskId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_user import ApiProvisioningV1AdminUser
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant import ApiProvisioningV1AdminTenant
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_workflow_definition import ApiProvisioningV1AdminTenantTenantIdWorkflowDefinition
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_user import ApiProvisioningV1AdminTenantTenantIdUser
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type import ApiProvisioningV1AdminTenantTenantIdTypologyType
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtype
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_seal_certificate import ApiProvisioningV1AdminTenantTenantIdSealCertificate
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_metadata import ApiProvisioningV1AdminTenantTenantIdMetadata
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_desk import ApiProvisioningV1AdminTenantTenantIdDesk
from iparapheur_provisioning.apis.paths.api_provisioning_v1_tenant_tenant_id_templates_template_type import ApiProvisioningV1TenantTenantIdTemplatesTemplateType
from iparapheur_provisioning.apis.paths.api_provisioning_v1_templates_template_type import ApiProvisioningV1TemplatesTemplateType
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_internal_metadata import ApiProvisioningV1AdminInternalMetadata

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API_PROVISIONING_V1_ADMIN_USER_USER_ID: ApiProvisioningV1AdminUserUserId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID: ApiProvisioningV1AdminTenantTenantId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_WORKFLOWDEFINITION_WORKFLOW_DEFINITION_KEY: ApiProvisioningV1AdminTenantTenantIdWorkflowDefinitionWorkflowDefinitionKey,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_USER_USER_ID: ApiProvisioningV1AdminTenantTenantIdUserUserId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TEMPLATES_TEMPLATE_TYPE: ApiProvisioningV1AdminTenantTenantIdTemplatesTemplateType,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_SEAL_CERTIFICATE_SEAL_CERTIFICATE_ID: ApiProvisioningV1AdminTenantTenantIdSealCertificateSealCertificateId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_METADATA_METADATA_ID: ApiProvisioningV1AdminTenantTenantIdMetadataMetadataId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_DESK_DESK_ID: ApiProvisioningV1AdminTenantTenantIdDeskDeskId,
        PathValues.API_PROVISIONING_V1_ADMIN_USER: ApiProvisioningV1AdminUser,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT: ApiProvisioningV1AdminTenant,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_WORKFLOWDEFINITION: ApiProvisioningV1AdminTenantTenantIdWorkflowDefinition,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_USER: ApiProvisioningV1AdminTenantTenantIdUser,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE: ApiProvisioningV1AdminTenantTenantIdTypologyType,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtype,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_SEAL_CERTIFICATE: ApiProvisioningV1AdminTenantTenantIdSealCertificate,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_METADATA: ApiProvisioningV1AdminTenantTenantIdMetadata,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_DESK: ApiProvisioningV1AdminTenantTenantIdDesk,
        PathValues.API_PROVISIONING_V1_TENANT_TENANT_ID_TEMPLATES_TEMPLATE_TYPE: ApiProvisioningV1TenantTenantIdTemplatesTemplateType,
        PathValues.API_PROVISIONING_V1_TEMPLATES_TEMPLATE_TYPE: ApiProvisioningV1TemplatesTemplateType,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_WORKFLOW_DEFINITION: ApiProvisioningV1AdminTenantTenantIdWorkflowDefinition,
        PathValues.API_PROVISIONING_V1_ADMIN_INTERNALMETADATA: ApiProvisioningV1AdminInternalMetadata,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_WORKFLOW_DEFINITION_WORKFLOW_DEFINITION_KEY: ApiProvisioningV1AdminTenantTenantIdWorkflowDefinitionWorkflowDefinitionKey,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API_PROVISIONING_V1_ADMIN_USER_USER_ID: ApiProvisioningV1AdminUserUserId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID: ApiProvisioningV1AdminTenantTenantId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_WORKFLOWDEFINITION_WORKFLOW_DEFINITION_KEY: ApiProvisioningV1AdminTenantTenantIdWorkflowDefinitionWorkflowDefinitionKey,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_USER_USER_ID: ApiProvisioningV1AdminTenantTenantIdUserUserId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TEMPLATES_TEMPLATE_TYPE: ApiProvisioningV1AdminTenantTenantIdTemplatesTemplateType,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_SEAL_CERTIFICATE_SEAL_CERTIFICATE_ID: ApiProvisioningV1AdminTenantTenantIdSealCertificateSealCertificateId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_METADATA_METADATA_ID: ApiProvisioningV1AdminTenantTenantIdMetadataMetadataId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_DESK_DESK_ID: ApiProvisioningV1AdminTenantTenantIdDeskDeskId,
        PathValues.API_PROVISIONING_V1_ADMIN_USER: ApiProvisioningV1AdminUser,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT: ApiProvisioningV1AdminTenant,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_WORKFLOWDEFINITION: ApiProvisioningV1AdminTenantTenantIdWorkflowDefinition,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_USER: ApiProvisioningV1AdminTenantTenantIdUser,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE: ApiProvisioningV1AdminTenantTenantIdTypologyType,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtype,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_SEAL_CERTIFICATE: ApiProvisioningV1AdminTenantTenantIdSealCertificate,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_METADATA: ApiProvisioningV1AdminTenantTenantIdMetadata,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_DESK: ApiProvisioningV1AdminTenantTenantIdDesk,
        PathValues.API_PROVISIONING_V1_TENANT_TENANT_ID_TEMPLATES_TEMPLATE_TYPE: ApiProvisioningV1TenantTenantIdTemplatesTemplateType,
        PathValues.API_PROVISIONING_V1_TEMPLATES_TEMPLATE_TYPE: ApiProvisioningV1TemplatesTemplateType,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_WORKFLOW_DEFINITION: ApiProvisioningV1AdminTenantTenantIdWorkflowDefinition,
        PathValues.API_PROVISIONING_V1_ADMIN_INTERNALMETADATA: ApiProvisioningV1AdminInternalMetadata,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_WORKFLOW_DEFINITION_WORKFLOW_DEFINITION_KEY: ApiProvisioningV1AdminTenantTenantIdWorkflowDefinitionWorkflowDefinitionKey,
    }
)
