ACCESO_ANALISTA_DIRECCION_TRANSITO = 21
ACCESO_ANALISTA_DIRECCION_OBRAS = 23
ACCESO_DIRECCION_TRANSITO_REVISOR = 19
ACCESO_REVISOR_SEREMITT = 1
ACCESO_ANALISTA_SEREMITT = 3
ACCESO_SEREMITT_SEREMI = 4
ACCESO_DIRECTOR_DIRECCION_TRANSITO = 22