"""Documentos SEIM"""
DOCTO_SEIM_CERTIFICADO_INGRESO = 'CERING'
DOCTO_SEIM_CERTIFICADO_INGRESO_MODIFICACION_PROYECTO = 'CERINGM'

DOCTO_SEIM_OFICIO_SOLICITUD_PRORROGA_INTERESADO = 'OFISOLPRO'
DOCTO_SEIM_OFICIO_SOLICITUD_PRORROGA_VENTANILLA_UNICA = 'SOLPRO'
DOCTO_SEIM_OFICIO_SOLICITUD_DESISTIMIENTO_INTERESADO = 'SOLDES'
DOCTO_SEIM_RESOLUCION_PRORROGA_RECHAZA = 'RESPRORE'

DOCTO_SEIM_OFICIO_CONSULTA_VENTANILLA_UNICA = 'OFICONVU'
DOCTO_SEIM_OFICIO_RESPUESTA_VENTANILLA_UNICA = 'OFIRESVU'

DOCTO_SEIM_RESOLUCION_MUNICIPAL_EVALUACION_IMIV_SIMPLE = 'RESMUNEVA'
DOCTO_SEIM_RESOLUCION_SEREMITT_EVALUACION_SIMPLE = 'RESSEREVA'

DOCTO_SEIM_RESOLUCION_SEREMITT_EVALUACION_IMIV_CONJUNTO = 'RESEVAC'
DOCTO_SEIM_RESOLUCION_MUNICIPAL_EVALUACION_IMIV_CONJUNTO = 'RESMEVAC'

DOCTO_SEIM_RESOLUCION_SEREMITT_EVALUACION_IMIV_OBSERVADO_SIMPLE = 'RESEVAOBS'
DOCTO_SEIM_RESOLUCION_SEREMITT_EVALUACION_IMIV_OBSERVADO_CONJUNTO = 'RESEVAOBC'

DOCTO_SEIM_RESOLUCION_MUNICIPAL_EVALUACION_IMIV_OBSERVADO_SIMPLE = 'RESMEVAOBS'
DOCTO_SEIM_RESOLUCION_MUNICIPAL_EVALUACION_IMIV_OBSERVADO_CONJUNTO = 'RESMEVAOBC'

DOCTO_SEIM_CERTIFICADO_SILENCIO_POSITIVO_SIMPLE = 'CERSILS'
DOCTO_SEIM_CERTIFICADO_SILENCIO_POSITIVO_CONJUNTO = 'CERSILC'

DOCTO_SEIM_RESOLUCION_EVALUACION_IMIV_MODIFICACION_SIMPLE = 'RESEVASM'
DOCTO_SEIM_RESOLUCION_EVALUACION_IMIV_MODIFICACION_CONJUNTO = 'RESEVACM'
DOCTO_SEIM_RESOLUCION_EVALUACION_IMIV_OBSERVADO_MODIFICACION_SIMPLE = 'RESEVAOBSM'
DOCTO_SEIM_RESOLUCION_EVALUACION_IMIV_OBSERVADO_MODIFICACION_CONJUNTO = 'RESEVAOBCM'

DOCTO_SEIM_CERTIFICADO_SUFICIENCIA = 'CERSUF'

DOCTO_SEIM_RESOLUCION_SEREMITT_DESISTIMIENTO = 'RESDES'
DOCTO_SEIM_RESOLUCION_MUNICIPAL_DESISTIMIENTO = 'RESDESM'

DOCTO_SEIM_SIMULACION_SIMPLE = 'SIMS'
DOCTO_SEIM_SIMULACION_CONJUNTO = 'SIMC'
DOCTO_SEIM_OFICIO_CATEGORIZACION_SIMPLE = 'OFICATS'
DOCTO_SEIM_OFICIO_CATEGORIZACION_CONJUNTO = 'OFICATC'
DOCTO_SEIM_DECLARACION_JURADA = 'DECLJUR'
DOCTO_SEIM_OFICIO_APROBACION_PRORROGA = 'OFIPROAP'
DOCTO_SEIM_OFICIO_RECHAZO_PRORROGA = 'OFIPRORE'
DOCTO_SEIM_CERTIFICADO_INGRESO_CORREGIDO = 'CERINGCORR'
DOCTO_SEIM_CERTIFICADO_EXENCION_462 = 'CEREXE462B'
DOCTO_SEIM_CERTIFICADO_EXENCION_463 = 'CEREXE463'

DOCTO_SEIM_CERTIFICADO_TRAMITACION = 'CERTRAM'
# Transicion
DOCTO_SEIM_DECLARACION_JURADA_TRANSICION = 'DECLJURTRAN'
DOCTO_SEIM_CERTIFICADO_INGRESO_SUFICIENCIA = 'CERINGSUF'
DOCTO_SEIM_CERTIFICADO_INGRESO_SUFICIENCIA_CORREGIDO = 'CERINGSUFCORR'

DOCTO_SEIM_RESOLUCION_RECHAZO_NO_CORREGIDO_MUNI = 'RESNOCOM'
DOCTO_SEIM_RESOLUCION_RECHAZO_NO_CORREGIDO_SEREMITT = 'RESNOCOS'

DOCTO_SEIM_RESOLUCION_SUFICIENCIA_OBSERVA = 'RESUFOB'
DOCTO_SEIM_RESOLUCION_SUFICIENCIA_APRUEBA_RECHAZA = 'RESUFAR'