import _abc
import abc
from proalgotrader_core.protocols.enums.symbol_type import SymbolType as SymbolType
from typing import ClassVar

TYPE_CHECKING: bool
__test__: dict

class SignalManagerProtocol(abc.ABC):
    _abc_impl: ClassVar[_abc._abc_data] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def initialize(self, *args, **kwargs): ...
    def next(self, *args, **kwargs): ...
