from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id.get import ApiForget
from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id.put import ApiForput
from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id.delete import ApiFordelete


class ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId(
    ApiForget,
    ApiForput,
    ApiFordelete,
):
    pass
