# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interconnection/handshake/op/sigmoid.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*interconnection/handshake/op/sigmoid.proto\x12\x19org.interconnection.v2.op\"J\n\x15SigmoidParamsProposal\x12\x1a\n\x12supported_versions\x18\x01 \x03(\x05\x12\x15\n\rsigmoid_modes\x18\x02 \x03(\x05\"<\n\x13SigmoidParamsResult\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x14\n\x0csigmoid_mode\x18\x02 \x01(\x05*G\n\x0bSigmoidMode\x12\x1c\n\x18SIGMOID_MODE_UNSPECIFIED\x10\x00\x12\x1a\n\x16SIGMOID_MODE_MINIMAX_1\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interconnection.handshake.op.sigmoid_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIGMOIDMODE._serialized_start=211
  _SIGMOIDMODE._serialized_end=282
  _SIGMOIDPARAMSPROPOSAL._serialized_start=73
  _SIGMOIDPARAMSPROPOSAL._serialized_end=147
  _SIGMOIDPARAMSRESULT._serialized_start=149
  _SIGMOIDPARAMSRESULT._serialized_end=209
# @@protoc_insertion_point(module_scope)
