from enum import Enum


class TensorDataType(Enum):
    TYPE_BYTES = "TYPE_BYTES"
    TYPE_BOOL = "TYPE_BOOL"
    TYPE_UINT8 = "TYPE_UINT8"
    TYPE_UINT16 = "TYPE_UINT16"
    TYPE_UINT32 = "TYPE_UINT32"
    TYPE_UINT64 = "TYPE_UINT64"
    TYPE_INT8 = "TYPE_INT8"
    TYPE_INT16 = "TYPE_INT16"
    TYPE_INT32 = "TYPE_INT32"
    TYPE_INT64 = "TYPE_INT64"
    TYPE_FP16 = "TYPE_FP16"
    TYPE_FP32 = "TYPE_FP32"
    TYPE_FP64 = "TYPE_FP64"
    TYPE_STRING = "TYPE_STRING"
    # TYPE_BF16 = "TYPE_BF16"
