# Generated by Django 3.2.24 on 2024-02-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimensiondate",
            name="ad_impressions",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="dimensiondate",
            name="ad_revenue",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="dimensiondate",
            name="new_users",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="dimensiondate",
            name="page_views",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="dimensiondate",
            name="sessions",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="dimensiondate",
            name="users",
            field=models.PositiveIntegerField(),
        ),
    ]
