# coding: utf-8

"""
    iparapheur

    iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic.   # noqa: E501

    The version of the OpenAPI document: DEVELOP
    Contact: iparapheur@libriciel.coop
    Generated by: https://openapi-generator.tech
"""

from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_desk.post import CreateDesk
from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_desk_desk_id.delete import DeleteDesk
from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_desk_desk_id.put import EditDesk
from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_desk_desk_id.get import GetDeskAsAdmin
from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_desk.get import ListDesks


class AdminDeskApi(
    CreateDesk,
    DeleteDesk,
    EditDesk,
    GetDeskAsAdmin,
    ListDesks,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
