import pandas as pd
from pathlib import Path
from typing import Any, Dict, Tuple

def get_ranges() -> Tuple[str, str]: ...
def get_json(item: Any) -> Dict[str, Any]: ...
def get_trading_days(data_path: Path) -> pd.DataFrame: ...
