# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.2.2
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist, constr
from authentik_client.models.model_enum import ModelEnum

class PermissionAssignRequest(BaseModel):
    """
    Request to assign a new permission  # noqa: E501
    """
    permissions: conlist(constr(strict=True, min_length=1)) = Field(...)
    model: Optional[ModelEnum] = None
    object_pk: Optional[constr(strict=True, min_length=1)] = None
    __properties = ["permissions", "model", "object_pk"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PermissionAssignRequest:
        """Create an instance of PermissionAssignRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PermissionAssignRequest:
        """Create an instance of PermissionAssignRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PermissionAssignRequest.parse_obj(obj)

        _obj = PermissionAssignRequest.parse_obj({
            "permissions": obj.get("permissions"),
            "model": obj.get("model"),
            "object_pk": obj.get("object_pk")
        })
        return _obj


