import enum
from typing import Callable, ClassVar

__test__: dict

class SegmentType(enum.Enum):
    __new__: ClassVar[Callable] = ...
    Equity: ClassVar[SegmentType] = ...
    Future: ClassVar[SegmentType] = ...
    Option: ClassVar[SegmentType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[object]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    _value_repr_: ClassVar[None] = ...
