# Generated by Django 3.2.24 on 2024-02-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="DimensionDate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dates", models.DateField()),
                ("users", models.IntegerField()),
                ("new_users", models.IntegerField()),
                ("page_views", models.IntegerField()),
                ("sessions", models.IntegerField()),
                ("ad_revenue", models.IntegerField()),
                ("ad_impressions", models.IntegerField()),
            ],
        ),
    ]
