# Generated by Django 4.2.9 on 2024-03-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenanet', '0003_remove_tenant_short_name_tenantconfiguration_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMeta',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tenanet.tenant')),
            ],
            options={
                'abstract': False,
                'swappable': 'TENANET_TENANT_META_MODEL',
            },
        ),
    ]
