# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from syndb_api_client.models.all_metadata import AllMetadata

class TestAllMetadata(unittest.TestCase):
    """AllMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AllMetadata:
        """Test AllMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AllMetadata`
        """
        model = AllMetadata()
        if include_optional:
            return AllMetadata(
                animal = [
                    syndb_api_client.models.animal_model_just_read.AnimalModelJustRead(
                        species = '', 
                        cultural_name = '', )
                    ],
                brain_region = [
                    syndb_api_client.models.brain_region_just_read.BrainRegionJustRead(
                        brain_structure = 'amygdaloid complex', 
                        direction = 'anterior', )
                    ],
                mutation = [
                    syndb_api_client.models.mutation_model_just_read.MutationModelJustRead(
                        gene = '', 
                        expression = 'knock-out', )
                    ],
                microscopy_names = [
                    ''
                    ],
                publication_dois = [
                    ''
                    ],
                all_datasets = [
                    ''
                    ],
                modifiable_datasets = [
                    56
                    ]
            )
        else:
            return AllMetadata(
                all_datasets = [
                    ''
                    ],
                modifiable_datasets = [
                    56
                    ],
        )
        """

    def testAllMetadata(self):
        """Test AllMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
