__test__: dict

class BaseTokenManager:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_token(self, *args, **kwargs): ...
    def initialize(self, *args, **kwargs): ...
    def set_access_token_file_name(self, *args, **kwargs): ...
    def set_token(self, *args, **kwargs): ...
