import proalgotrader_core.token_managers.base_token_manager
from proalgotrader_core.helpers.get_totp import get_totp as get_totp
from proalgotrader_core.token_managers.base_token_manager import BaseTokenManager as BaseTokenManager

API_URL: str
AUTH_URL: str
URL_SEND_LOGIN_OTP_V2: str
URL_TOKEN: str
URL_VALIDATE_AUTH_CODE: str
URL_VERIFY_PIN_V2: str
URL_VERIFY_TOTP: str
__test__: dict

class FyersTokenManager(proalgotrader_core.token_managers.base_token_manager.BaseTokenManager):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_auth_code(self, *args, **kwargs): ...
    def get_token(self, *args, **kwargs): ...
    def login_otp(self, *args, **kwargs): ...
    def set_token(self, *args, **kwargs): ...
    def verify_otp(self, *args, **kwargs): ...
    def verify_pin(self, *args, **kwargs): ...
