
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-20T15:04:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "29913be0148ae536ea495a91c7a7a3a74660acff",
 "version": "2024.3.20.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
