# coding: utf-8

"""
    iparapheur

    iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic.   # noqa: E501

    The version of the OpenAPI document: DEVELOP
    Contact: iparapheur@libriciel.coop
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from iparapheur_internal import schemas  # noqa: F401


class StampType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "SIGNATURE": "SIGNATURE",
            "TEXT": "TEXT",
            "IMAGE": "IMAGE",
            "METADATA": "METADATA",
        }
    
    @schemas.classproperty
    def SIGNATURE(cls):
        return cls("SIGNATURE")
    
    @schemas.classproperty
    def TEXT(cls):
        return cls("TEXT")
    
    @schemas.classproperty
    def IMAGE(cls):
        return cls("IMAGE")
    
    @schemas.classproperty
    def METADATA(cls):
        return cls("METADATA")
