from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_seal_certificate_seal_certificate_id.get import ApiForget
from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_seal_certificate_seal_certificate_id.put import ApiForput
from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_seal_certificate_seal_certificate_id.delete import ApiFordelete


class ApiProvisioningV1AdminTenantTenantIdSealCertificateSealCertificateId(
    ApiForget,
    ApiForput,
    ApiFordelete,
):
    pass
