from proalgotrader_core.helpers.get_data_path import get_data_path as get_data_path
from proalgotrader_core.helpers.get_trading_days import get_trading_days as get_trading_days
from proalgotrader_core.project import Project as Project

TYPE_CHECKING: bool
__test__: dict

class AlgoSession:
    def __init__(self, *args, **kwargs) -> None: ...
    def fetch_ranges(self, *args, **kwargs): ...
    def get_current_candle(self, *args, **kwargs): ...
    def get_expires(self, *args, **kwargs): ...
    def get_market_status(self, *args, **kwargs): ...
    def get_warmups_days(self, *args, **kwargs): ...
    def validate_market_status(self, *args, **kwargs): ...
    @property
    def current_date(self): ...
    @property
    def current_datetime(self): ...
    @property
    def current_time(self): ...
    @property
    def current_timestamp(self): ...
