from proalgotrader_core.broker_symbol import BrokerSymbol as BrokerSymbol
from proalgotrader_core.protocols.enums.segment_type import SegmentType as SegmentType

TYPE_CHECKING: bool
__test__: dict

class Chart:
    def __init__(self, *args, **kwargs) -> None: ...
    def is_new_candle(self, *args, **kwargs): ...
    def next(self, *args, **kwargs): ...
    @property
    def current_candle(self): ...
    @property
    def data(self): ...
    @property
    def ltp(self): ...
