from proalgotrader_core.algo_session import AlgoSession as AlgoSession
from proalgotrader_core.api import Api as Api
from proalgotrader_core.bar import Bar as Bar
from proalgotrader_core.broker_symbol import BrokerSymbol as BrokerSymbol
from proalgotrader_core.tick import Tick as Tick
from proalgotrader_core.token_managers.fyers_token_manager import FyersTokenManager as FyersTokenManager

__test__: dict

class DataManager:
    def __init__(self, *args, **kwargs) -> None: ...
    def close_connection(self, *args, **kwargs): ...
    def fetch_bars(self, *args, **kwargs): ...
    def fetch_quotes(self, *args, **kwargs): ...
    def initialize(self, *args, **kwargs): ...
    def on_message(self, *args, **kwargs): ...
    def start_connection(self, *args, **kwargs): ...
    def subscribe(self, *args, **kwargs): ...
