TYPE_CHECKING: bool
__test__: dict

class NotificationManager:
    def __init__(self, *args, **kwargs) -> None: ...
    def connect(self, *args, **kwargs): ...
    def disconnect(self, *args, **kwargs): ...
    def run_websocket(self, *args, **kwargs): ...
    def send_message(self, *args, **kwargs): ...
    def subscribe(self, *args, **kwargs): ...
