from proalgotrader_core.broker_symbol import BrokerSymbol as BrokerSymbol

TYPE_CHECKING: bool
__test__: dict

class Order:
    def __init__(self, *args, **kwargs) -> None: ...
    def initialize(self, *args, **kwargs): ...
    @property
    def is_completed(self): ...
    @property
    def is_pending(self): ...
