from proalgotrader_core.broker_symbol import BrokerSymbol as BrokerSymbol
from proalgotrader_core.brokers.base_broker import BaseBroker as BaseBroker
from proalgotrader_core.chart import Chart as Chart

__test__: dict

class ChartManager:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_chart(self, *args, **kwargs): ...
    def register_chart(self, *args, **kwargs): ...
    @property
    def charts(self): ...
