from proalgotrader_core.broker_symbol import BrokerSymbol as BrokerSymbol
from proalgotrader_core.protocols.enums.position_type import PositionType as PositionType
from proalgotrader_core.protocols.enums.product_type import ProductType as ProductType
from proalgotrader_core.protocols.position_manager import PositionManagerProtocol as PositionManagerProtocol
from proalgotrader_core.risk_reward import RiskReward as RiskReward

TYPE_CHECKING: bool
__test__: dict

class Position:
    def __init__(self, *args, **kwargs) -> None: ...
    def exit(self, *args, **kwargs): ...
    def get_risk_reward(self, *args, **kwargs): ...
    def initialize(self, *args, **kwargs): ...
    def next(self, *args, **kwargs): ...
    def on_after_market_closed(self, *args, **kwargs): ...
    @property
    def is_buy(self): ...
    @property
    def is_sell(self): ...
    @property
    def pnl(self): ...
    @property
    def pnl_percent(self): ...
    @property
    def should_square_off(self): ...
