from proalgotrader_core.broker_symbol import BrokerSymbol as BrokerSymbol
from proalgotrader_core.protocols.enums.position_type import PositionType as PositionType

TYPE_CHECKING: bool
__test__: dict

class Trade:
    def __init__(self, *args, **kwargs) -> None: ...
    def initialize(self, *args, **kwargs): ...
    @property
    def is_buy(self): ...
    @property
    def is_sell(self): ...
    @property
    def pnl(self): ...
    @property
    def pnl_percent(self): ...
