import typing_extensions

from iparapheur_internal.paths import PathValues
from iparapheur_internal.apis.paths.api_internal_current_user_password import ApiInternalCurrentUserPassword
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_layer_layer_id import ApiInternalAdminTenantTenantIdLayerLayerId
from iparapheur_internal.apis.paths.api_internal_admin_config_chorus_configuration import ApiInternalAdminConfigChorusConfiguration
from iparapheur_internal.apis.paths.api_internal_tenant_tenant_id_templates_template_type_example import ApiInternalTenantTenantIdTemplatesTemplateTypeExample
from iparapheur_internal.apis.paths.api_internal_tenant_tenant_id_folder_folder_id_signature_report import ApiInternalTenantTenantIdFolderFolderIdSignatureReport
from iparapheur_internal.apis.paths.api_internal_tenant_tenant_id_desk_desk_id_search_state import ApiInternalTenantTenantIdDeskDeskIdSearchState
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_test_signature_pdf_template import ApiInternalAdminTenantTenantIdTestSignaturePdfTemplate
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_test_mail_template import ApiInternalAdminTenantTenantIdTestMailTemplate
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_test_docket_pdf_template import ApiInternalAdminTenantTenantIdTestDocketPdfTemplate
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_layer import ApiInternalAdminTenantTenantIdLayer
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_layer_layer_id_stamp import ApiInternalAdminTenantTenantIdLayerLayerIdStamp
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_layer_example_pdf import ApiInternalAdminTenantTenantIdLayerExamplePdf
from iparapheur_internal.apis.paths.api_internal_tenant_tenant_id_typology_type_type_id import ApiInternalTenantTenantIdTypologyTypeTypeId
from iparapheur_internal.apis.paths.api_internal_tenant_tenant_id_typology_type_type_id_subtype_subtype_id import ApiInternalTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId
from iparapheur_internal.apis.paths.api_internal_tenant_tenant_id_desk_desk_id_workflow_definition_workflow_definition_key import ApiInternalTenantTenantIdDeskDeskIdWorkflowDefinitionWorkflowDefinitionKey
from iparapheur_internal.apis.paths.api_internal_tenant_tenant_id_desk_desk_id_associated_desks import ApiInternalTenantTenantIdDeskDeskIdAssociatedDesks
from iparapheur_internal.apis.paths.api_internal_server_info_password_policies import ApiInternalServerInfoPasswordPolicies
from iparapheur_internal.apis.paths.api_internal_server_info_gdpr import ApiInternalServerInfoGdpr
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_typology import ApiInternalAdminTenantTenantIdTypology
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_trash_bin import ApiInternalAdminTenantTenantIdTrashBin
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_seal_certificate_seal_certificate_id_subtype_usage import ApiInternalAdminTenantTenantIdSealCertificateSealCertificateIdSubtypeUsage
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_seal_certificate_seal_certificate_id_signature_image import ApiInternalAdminTenantTenantIdSealCertificateSealCertificateIdSignatureImage
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_desk import ApiInternalAdminTenantTenantIdDesk
from iparapheur_internal.apis.paths.api_internal_admin_config_chorus import ApiInternalAdminConfigChorus
from iparapheur_internal.apis.paths.api_internal_admin_tenant_tenant_id_layer_layer_id_stamp_stamp_id import ApiInternalAdminTenantTenantIdLayerLayerIdStampStampId

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API_INTERNAL_CURRENT_USER_PASSWORD: ApiInternalCurrentUserPassword,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER_LAYER_ID: ApiInternalAdminTenantTenantIdLayerLayerId,
        PathValues.API_INTERNAL_ADMIN_CONFIG_CHORUSCONFIGURATION: ApiInternalAdminConfigChorusConfiguration,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_TEMPLATES_TEMPLATE_TYPE_EXAMPLE: ApiInternalTenantTenantIdTemplatesTemplateTypeExample,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_FOLDER_FOLDER_ID_SIGNATUREREPORT: ApiInternalTenantTenantIdFolderFolderIdSignatureReport,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_DESK_DESK_ID_SEARCH_STATE: ApiInternalTenantTenantIdDeskDeskIdSearchState,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TESTSIGNATUREPDFTEMPLATE: ApiInternalAdminTenantTenantIdTestSignaturePdfTemplate,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TESTMAILTEMPLATE: ApiInternalAdminTenantTenantIdTestMailTemplate,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TESTDOCKETPDFTEMPLATE: ApiInternalAdminTenantTenantIdTestDocketPdfTemplate,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER: ApiInternalAdminTenantTenantIdLayer,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER_LAYER_ID_STAMP: ApiInternalAdminTenantTenantIdLayerLayerIdStamp,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER_EXAMPLEPDF: ApiInternalAdminTenantTenantIdLayerExamplePdf,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID: ApiInternalTenantTenantIdTypologyTypeTypeId,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID: ApiInternalTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_DESK_DESK_ID_WORKFLOWDEFINITION_WORKFLOW_DEFINITION_KEY: ApiInternalTenantTenantIdDeskDeskIdWorkflowDefinitionWorkflowDefinitionKey,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_DESK_DESK_ID_ASSOCIATED_DESKS: ApiInternalTenantTenantIdDeskDeskIdAssociatedDesks,
        PathValues.API_INTERNAL_SERVER_INFO_PASSWORD_POLICIES: ApiInternalServerInfoPasswordPolicies,
        PathValues.API_INTERNAL_SERVER_INFO_GDPR: ApiInternalServerInfoGdpr,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TYPOLOGY: ApiInternalAdminTenantTenantIdTypology,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TRASHBIN: ApiInternalAdminTenantTenantIdTrashBin,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_SEAL_CERTIFICATE_SEAL_CERTIFICATE_ID_SUBTYPE_USAGE: ApiInternalAdminTenantTenantIdSealCertificateSealCertificateIdSubtypeUsage,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_SEAL_CERTIFICATE_SEAL_CERTIFICATE_ID_SIGNATURE_IMAGE: ApiInternalAdminTenantTenantIdSealCertificateSealCertificateIdSignatureImage,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_DESK: ApiInternalAdminTenantTenantIdDesk,
        PathValues.API_INTERNAL_ADMIN_CONFIG_CHORUS: ApiInternalAdminConfigChorus,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER_LAYER_ID_STAMP_STAMP_ID: ApiInternalAdminTenantTenantIdLayerLayerIdStampStampId,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API_INTERNAL_CURRENT_USER_PASSWORD: ApiInternalCurrentUserPassword,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER_LAYER_ID: ApiInternalAdminTenantTenantIdLayerLayerId,
        PathValues.API_INTERNAL_ADMIN_CONFIG_CHORUSCONFIGURATION: ApiInternalAdminConfigChorusConfiguration,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_TEMPLATES_TEMPLATE_TYPE_EXAMPLE: ApiInternalTenantTenantIdTemplatesTemplateTypeExample,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_FOLDER_FOLDER_ID_SIGNATUREREPORT: ApiInternalTenantTenantIdFolderFolderIdSignatureReport,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_DESK_DESK_ID_SEARCH_STATE: ApiInternalTenantTenantIdDeskDeskIdSearchState,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TESTSIGNATUREPDFTEMPLATE: ApiInternalAdminTenantTenantIdTestSignaturePdfTemplate,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TESTMAILTEMPLATE: ApiInternalAdminTenantTenantIdTestMailTemplate,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TESTDOCKETPDFTEMPLATE: ApiInternalAdminTenantTenantIdTestDocketPdfTemplate,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER: ApiInternalAdminTenantTenantIdLayer,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER_LAYER_ID_STAMP: ApiInternalAdminTenantTenantIdLayerLayerIdStamp,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER_EXAMPLEPDF: ApiInternalAdminTenantTenantIdLayerExamplePdf,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID: ApiInternalTenantTenantIdTypologyTypeTypeId,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID: ApiInternalTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_DESK_DESK_ID_WORKFLOWDEFINITION_WORKFLOW_DEFINITION_KEY: ApiInternalTenantTenantIdDeskDeskIdWorkflowDefinitionWorkflowDefinitionKey,
        PathValues.API_INTERNAL_TENANT_TENANT_ID_DESK_DESK_ID_ASSOCIATED_DESKS: ApiInternalTenantTenantIdDeskDeskIdAssociatedDesks,
        PathValues.API_INTERNAL_SERVER_INFO_PASSWORD_POLICIES: ApiInternalServerInfoPasswordPolicies,
        PathValues.API_INTERNAL_SERVER_INFO_GDPR: ApiInternalServerInfoGdpr,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TYPOLOGY: ApiInternalAdminTenantTenantIdTypology,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_TRASHBIN: ApiInternalAdminTenantTenantIdTrashBin,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_SEAL_CERTIFICATE_SEAL_CERTIFICATE_ID_SUBTYPE_USAGE: ApiInternalAdminTenantTenantIdSealCertificateSealCertificateIdSubtypeUsage,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_SEAL_CERTIFICATE_SEAL_CERTIFICATE_ID_SIGNATURE_IMAGE: ApiInternalAdminTenantTenantIdSealCertificateSealCertificateIdSignatureImage,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_DESK: ApiInternalAdminTenantTenantIdDesk,
        PathValues.API_INTERNAL_ADMIN_CONFIG_CHORUS: ApiInternalAdminConfigChorus,
        PathValues.API_INTERNAL_ADMIN_TENANT_TENANT_ID_LAYER_LAYER_ID_STAMP_STAMP_ID: ApiInternalAdminTenantTenantIdLayerLayerIdStampStampId,
    }
)
