import typing
import bpy_types

GenericType = typing.TypeVar("GenericType")

class BUILTIN_KSI_Available(bpy_types.KeyingSetInfo):
    bl_idname: typing.Any
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _ksi, _context, ks, data):
        """

        :param _ksi:
        :type _ksi:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, context):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_BendyBones(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _ksi, _context, ks, data):
        """

        :param _ksi:
        :type _ksi:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, _ksi, context):
        """

        :param _ksi:
        :type _ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_DeltaLocation(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _context, ks, data):
        """

        :param self:
        :type self:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, _ksi, context):
        """

        :param _ksi:
        :type _ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_DeltaRotation(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _context, ks, data):
        """

        :param self:
        :type self:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, _ksi, context):
        """

        :param _ksi:
        :type _ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_DeltaScale(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _context, ks, data):
        """

        :param self:
        :type self:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, _ksi, context):
        """

        :param _ksi:
        :type _ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_LocRot(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, data):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_LocRotScale(bpy_types.KeyingSetInfo):
    bl_idname: typing.Any
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, data):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_LocRotScaleCProp(bpy_types.KeyingSetInfo):
    bl_idname: typing.Any
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, data):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_LocScale(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, data):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_Location(bpy_types.KeyingSetInfo):
    bl_idname: typing.Any
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _ksi, _context, ks, data):
        """

        :param _ksi:
        :type _ksi:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_RotScale(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, data):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_Rotation(bpy_types.KeyingSetInfo):
    bl_idname: typing.Any
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _ksi, _context, ks, data):
        """

        :param _ksi:
        :type _ksi:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_Scaling(bpy_types.KeyingSetInfo):
    bl_idname: typing.Any
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _ksi, _context, ks, data):
        """

        :param _ksi:
        :type _ksi:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_VisualLoc(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_options: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _ksi, _context, ks, data):
        """

        :param _ksi:
        :type _ksi:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_VisualLocRot(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_options: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, data):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_VisualLocRotScale(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_options: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, data):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_VisualLocScale(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_options: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, data):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_VisualRot(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_options: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _ksi, _context, ks, data):
        """

        :param _ksi:
        :type _ksi:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_VisualRotScale(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_options: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, data):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_VisualScaling(bpy_types.KeyingSetInfo):
    bl_label: typing.Any
    bl_options: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, _ksi, _context, ks, data):
        """

        :param _ksi:
        :type _ksi:
        :param _context:
        :type _context:
        :param ks:
        :type ks:
        :param data:
        :type data:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, ksi, context, ks):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, ksi, context):
        """

        :param ksi:
        :type ksi:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class WholeCharacterMixin:
    badBonePrefixes: typing.Any

    def addProp(self, ks, bone, prop, index, use_groups):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        :param prop:
        :type prop:
        :param index:
        :type index:
        :param use_groups:
        :type use_groups:
        """
        ...

    def doBBone(self, context, ks, pchan):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param pchan:
        :type pchan:
        """
        ...

    def doCustomProps(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doLoc(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doRot3d(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doRot4d(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doScale(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def generate(self, context, ks, bone):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def iterator(self, context, ks):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def poll(self, context):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        """
        ...

class BUILTIN_KSI_WholeCharacter(WholeCharacterMixin, bpy_types.KeyingSetInfo):
    badBonePrefixes: typing.Any
    bl_idname: typing.Any
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def addProp(self, ks, bone, prop, index, use_groups):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        :param prop:
        :type prop:
        :param index:
        :type index:
        :param use_groups:
        :type use_groups:
        """
        ...

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def doBBone(self, context, ks, pchan):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param pchan:
        :type pchan:
        """
        ...

    def doCustomProps(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doLoc(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doRot3d(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doRot4d(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doScale(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, bone):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, context, ks):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, context):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

class BUILTIN_KSI_WholeCharacterSelected(WholeCharacterMixin, bpy_types.KeyingSetInfo):
    badBonePrefixes: typing.Any
    bl_idname: typing.Any
    bl_label: typing.Any
    bl_rna: typing.Any
    id_data: typing.Any

    def addProp(self, ks, bone, prop, index, use_groups):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        :param prop:
        :type prop:
        :param index:
        :type index:
        :param use_groups:
        :type use_groups:
        """
        ...

    def as_pointer(self): ...
    def bl_rna_get_subclass(self): ...
    def bl_rna_get_subclass_py(self): ...
    def doBBone(self, context, ks, pchan):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param pchan:
        :type pchan:
        """
        ...

    def doCustomProps(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doLoc(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doRot3d(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doRot4d(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def doScale(self, ks, bone):
        """

        :param self:
        :type self:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def driver_add(self): ...
    def driver_remove(self): ...
    def generate(self, context, ks, bone):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        :param bone:
        :type bone:
        """
        ...

    def get(self): ...
    def id_properties_clear(self): ...
    def id_properties_ensure(self): ...
    def id_properties_ui(self): ...
    def is_property_hidden(self): ...
    def is_property_overridable_library(self): ...
    def is_property_readonly(self): ...
    def is_property_set(self): ...
    def items(self): ...
    def iterator(self, context, ks):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        :param ks:
        :type ks:
        """
        ...

    def keyframe_delete(self): ...
    def keyframe_insert(self): ...
    def keys(self): ...
    def path_from_id(self): ...
    def path_resolve(self): ...
    def poll(self, context):
        """

        :param self:
        :type self:
        :param context:
        :type context:
        """
        ...

    def pop(self): ...
    def property_overridable_library_set(self): ...
    def property_unset(self): ...
    def type_recast(self): ...
    def values(self): ...

def register(): ...
def unregister(): ...
