from typing import *

def _create(obj:Any) -> object | None: ...
def _get(obj:object) -> Any: ...
def _getaddr(obj:object) -> str: ...
def _set(obj:object,val:Self) -> bool: ...
def _free(obj:object) -> bool: ...